#!/bin/bash -o errexit -o nounset -o verbose

# Return to $PWD at the end.
trap "cd $PWD; exit" INT TERM EXIT

# Get top-level repository directory.
TOPDIR="$(git rev-parse --show-toplevel)"
cd "$TOPDIR"

source version

# Check out the auxiliary build files directory.
svn checkout -r $REVISION svn://tug.org/texlive/trunk/Build/source/build-aux

# Check out the kpathsea source directory.
(
  dir=texk/kpathsea
  svn checkout -r $REVISION svn://tug.org/texlive/trunk/Build/source/$dir $dir
)

# Check out the texlive scripts directory.
(
  dir=texk/texlive
  svn checkout -r $REVISION svn://tug.org/texlive/trunk/Build/source/$dir $dir
  # See .gitignore for ignored files.
)

# Check out directories only found in the Master directory.
(
  dir="texmf-dist/fonts/map/dvips/tetex"
  svn checkout -r $REVISION svn://tug.org/texlive/trunk/Master/$dir $dir
)
(
  dir="texmf-dist/texconfig"
  svn checkout -r $REVISION svn://tug.org/texlive/trunk/Master/$dir $dir
  # See .gitignore for ignored files.
)
(
  dir="texmf-dist/web2c"
  svn checkout -r $REVISION svn://tug.org/texlive/trunk/Master/$dir $dir
  # See .gitignore for ignored files.
)
(
  dir="texmf-dist/scripts/texlive"
  svn checkout -r $REVISION svn://tug.org/texlive/trunk/Master/$dir $dir/
  # See .gitignore for ignored files.
)

# Check out files only found in the Master directory.
(
  dir="texmf-dist/doc/info"
  mkdir -p info
  svn export --force -r $REVISION svn://tug.org/texlive/trunk/Master/$dir/tds.info info/
)
