#!/bin/bash -o errexit -o nounset -o verbose

# Return to $PWD at the end.
trap "cd $PWD; exit" INT TERM EXIT

# Get top-level repository directory.
TOPDIR="$(git rev-parse --show-toplevel)"
cd "$TOPDIR"

source version

# Exit if there are unstaged changes
git diff-files --quiet --

# Exit if there are uncommitted changes
git diff-index --quiet HEAD --

# Delete local and remote pre-release tags. If a tag does not exist, don't fail.
if [[ "$VERSION" == *pre ]]; then
  git tag --delete "$VERSION" || true
  git push --delete origin "$VERSION" || true
else
  # If the version was previously a pre-release, delete the pre-release tags.
  git tag --delete "${VERSION}pre" || true
  git push --delete origin "${VERSION}pre" || true
fi

# Tag the version. This will fail if the tag already exists.
git tag -a "$VERSION" -m "r$REVISION"

# Push all changes and tags.
git push --follow-tags
