#!/bin/bash -o errexit -o nounset -o verbose

# Return to $PWD at the end.
trap "cd $PWD; exit" INT TERM EXIT

# Get top-level repository directory.
TOPDIR="$(git rev-parse --show-toplevel)"
cd "$TOPDIR"

# Get the remote repository base name.
REPO="$(basename -s .git $(git remote get-url origin))"

source version

TESTDIR="$TOPDIR/test"

# Create a test directory and navigate to it.
mkdir -p "$TESTDIR"
cd "$TESTDIR"

ARCHIVE="$VERSION.tar.gz"

# Download the release archive.
rm -f "$ARCHIVE"
curl -fsSLO "https://github.com/texbrew/$REPO/archive/$ARCHIVE"

ARCHIVEDIR="$TESTDIR/$REPO-$VERSION"

# Extract the archive.
rm -rf "$ARCHIVEDIR"
tar xzf "$ARCHIVE"

# Configure and build kpathsea.
cd "$ARCHIVEDIR/texk/kpathsea"
./configure
make

# Configure texlive scripts. No building necessary.
cd "$ARCHIVEDIR/texk/texlive"
./configure
