#!/bin/bash -o errexit -o nounset -o verbose

# Return to $PWD at the end.
trap "cd $PWD; exit" INT TERM EXIT

# Get top-level repository directory.
TOP="$(git rev-parse --show-toplevel)"
cd "$TOP"

# Get the remote repository base name.
REPO="$(basename -s .git $(git remote get-url origin))"

source version

# Create a test directory and navigate to it.
mkdir -p test
cd test

ARCHIVE="$VERSION.tar.gz"

# Download the release archive.
rm -f "$ARCHIVE"
curl -fsSLO "https://github.com/texbrew/$REPO/archive/$ARCHIVE"

DIR="$REPO-$VERSION"

# Extract the archive.
rm -rf "$DIR"
tar xzf "$ARCHIVE"

# Configure. No building: it's only scripts.
cd "$DIR/texk/texlive"
./configure
